service: eth-gas-fee-checker

plugins:
  - serverless-dotenv-plugin # add plugin

useDotenv: true # add this for local

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  checkGasFees:
    handler: handler.checkGasFees
    events:
      - http:
          path: /
          method: get
